### ISSUE TITLE
Error while submitting job

### ISSUE THREAD

**Issue by nikhilhatwar** [chunshen1987/iEBE-MUSIC#2]
Dear Chun Sir,

I am running a docker _iebe-music_ container in a single server with 24 cores. And I could not install `qsub` to run the following job script in the container: 
 `/home/iEBE-MUSIC/playground/event_0/submit_job.pbs`.

Hence I simply typed the contents of above script in the container terminal, which were:
```
seed_add=${1:-0}
python3 hydro_plus_UrQMD_driver.py 3DMCGlauber_dynamical self 1 0 1 1 False False False $seed_add 0.4 > run.log
```
I hope this still works to run the job.

This gave me the following error:

```
root@f440db46d444:/home/iEBE-MUSIC/playground/event_0# python3 hydro_plus_UrQMD_driver.py 3DMCGlauber_dynamical self 1 0 1 1 False False False $seed_add 0.4 > run.log
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
mv: cannot stat '3dMCGlauber/strings_event_0.dat': No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'strings_event_0.dat' -> 'MUSIC/initial/strings.dat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydro_plus_UrQMD_driver.py", line 516, in <module>
    main(para_dict)
  File "hydro_plus_UrQMD_driver.py", line 381, in main
    shutil.move(ifile, "MUSIC/initial/strings.dat")
  File "/usr/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'strings_event_0.dat'
```

I guess there is a problem in file `hydro_plus_UrQMD_driver.py`. 
Could you please look into this error and suggest ways of resolving it.

**Comment by chunshen1987** [comment]
Hi,

Sorry for the errors! I am actively developing the 3D-MCGlauber model and the current main branch is out-of-date. You can try to run simulations with the docker images (tag: v0.5, v1.0, or dev).

Let me know if you have any questions. Thanks!

Sincerely,
Chun Shen

**Comment by nikhilhatwar** [comment]
I tried running tag:v1.0 and the code executed. Thank you.
